all:
  children:
    kube-masters:
      hosts:
        master1:
          ansible_host: 10.1.2.11
          rke2_node_ip: 10.1.2.11
        master2:
          ansible_host: 10.1.2.12
          rke2_node_ip: 10.1.2.12
        master3:
          ansible_host: 10.1.2.13
          rke2_node_ip: 10.1.2.13
    kube-workers:
      hosts:
        worker1:
          ansible_host: 10.1.2.21
          rke2_node_ip: 10.1.2.21
        worker2:
          ansible_host: 10.1.2.22
          rke2_node_ip: 10.1.2.22
        worker3:
          ansible_host: 10.1.2.23
          rke2_node_ip: 10.1.2.23
