# /etc/rancher/rke2/config.yaml
# Joining control plane nodes
# Deploy AFTER master-init node is up and VIP is live

server: "https://<VIP>:9345"
token: "<TOKEN>"

tls-san:
  - "<API_FQDN>"
  - "<VIP>"        # VIP
  - "<MASTER1_IP>" # master1
  - "<MASTER2_IP>" # master2
  - "<MASTER3_IP>" # master3

node-ip: <NODE_IP>
advertise-address: <NODE_IP>

cni: none
disable-kube-proxy: true
cluster-domain: <CLUSTER_DOMAIN>
cluster-cidr: <CLUSTER_CIDR>
service-cidr: <SERVICE_CIDR>

etcd-snapshot-schedule-cron: "0 */6 * * *"
etcd-snapshot-retention: 10

disable:
  - rke2-ingress-nginx

node-taint:
  - "node-role.kubernetes.io/control-plane=true:NoSchedule"
